// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"time"
)

// Defines values for PlaybackEventType.
const (
	PlaybackEventTypeChunkStarted     PlaybackEventType = "chunk.started"
	PlaybackEventTypePlaybackFailed   PlaybackEventType = "playback.failed"
	PlaybackEventTypePlaybackFinished PlaybackEventType = "playback.finished"
	PlaybackEventTypePlaybackPaused   PlaybackEventType = "playback.paused"
	PlaybackEventTypePlaybackResumed  PlaybackEventType = "playback.resumed"
	PlaybackEventTypePlaybackSnapshot PlaybackEventType = "playback.snapshot"
	PlaybackEventTypePlaybackStarted  PlaybackEventType = "playback.started"
	PlaybackEventTypePlaybackStopped  PlaybackEventType = "playback.stopped"
	PlaybackEventTypePlaybackStopping PlaybackEventType = "playback.stopping"
	PlaybackEventTypePositionUpdated  PlaybackEventType = "position.updated"
	PlaybackEventTypeProgressUpdated  PlaybackEventType = "progress.updated"
)

// Valid indicates whether the value is a known member of the PlaybackEventType enum.
func (e PlaybackEventType) Valid() bool {
	switch e {
	case PlaybackEventTypeChunkStarted:
		return true
	case PlaybackEventTypePlaybackFailed:
		return true
	case PlaybackEventTypePlaybackFinished:
		return true
	case PlaybackEventTypePlaybackPaused:
		return true
	case PlaybackEventTypePlaybackResumed:
		return true
	case PlaybackEventTypePlaybackSnapshot:
		return true
	case PlaybackEventTypePlaybackStarted:
		return true
	case PlaybackEventTypePlaybackStopped:
		return true
	case PlaybackEventTypePlaybackStopping:
		return true
	case PlaybackEventTypePositionUpdated:
		return true
	case PlaybackEventTypeProgressUpdated:
		return true
	default:
		return false
	}
}

// Defines values for PlaybackStateErrorCode.
const (
	PlaybackStateErrorCodeInternalError    PlaybackStateErrorCode = "internal_error"
	PlaybackStateErrorCodePlaybackStopping PlaybackStateErrorCode = "playback_stopping"
)

// Valid indicates whether the value is a known member of the PlaybackStateErrorCode enum.
func (e PlaybackStateErrorCode) Valid() bool {
	switch e {
	case PlaybackStateErrorCodeInternalError:
		return true
	case PlaybackStateErrorCodePlaybackStopping:
		return true
	default:
		return false
	}
}

// Defines values for PlaybackStateState.
const (
	Failed   PlaybackStateState = "failed"
	Finished PlaybackStateState = "finished"
	Paused   PlaybackStateState = "paused"
	Playing  PlaybackStateState = "playing"
	Stopped  PlaybackStateState = "stopped"
	Stopping PlaybackStateState = "stopping"
)

// Valid indicates whether the value is a known member of the PlaybackStateState enum.
func (e PlaybackStateState) Valid() bool {
	switch e {
	case Failed:
		return true
	case Finished:
		return true
	case Paused:
		return true
	case Playing:
		return true
	case Stopped:
		return true
	case Stopping:
		return true
	default:
		return false
	}
}

// AddBookRequest defines model for AddBookRequest.
type AddBookRequest struct {
	// Path Absolute or relative local path to a UTF-8 text file.
	//
	// Example: C:\Books\novel.txt
	Path string `json:"path"`

	// Title Example: Novel
	Title string `json:"title,omitempty,omitzero"`
}

// Book Public book metadata. Filesystem paths and progress files are internal and are never returned by the API.
type Book struct {
	// ID Example: book-1
	ID    string `json:"id"`
	Size  int64  `json:"size"`
	Title string `json:"title"`
}

// BooksResponse defines model for BooksResponse.
type BooksResponse struct {
	Books []Book `json:"books"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Example: book_modified
	Code     string        `json:"code"`
	Error    string        `json:"error"`
	Playback PlaybackState `json:"playback,omitempty,omitzero"`
}

// PlaybackEvent defines model for PlaybackEvent.
type PlaybackEvent struct {
	Playback PlaybackState     `json:"playback"`
	Seq      int64             `json:"seq"`
	Time     time.Time         `json:"time"`
	Type     PlaybackEventType `json:"type"`
}

// PlaybackEventType defines model for PlaybackEvent.Type.
type PlaybackEventType string

// PlaybackState defines model for PlaybackState.
type PlaybackState struct {
	// BookID Example: book-1
	BookID          string                 `json:"book_id,omitempty,omitzero"`
	ChunkSize       int                    `json:"chunk_size,omitempty,omitzero"`
	CurrentByte     int64                  `json:"current_byte"`
	Error           string                 `json:"error,omitempty,omitzero"`
	ErrorCode       PlaybackStateErrorCode `json:"error_code,omitempty,omitzero"`
	ProgressPercent float64                `json:"progress_percent"`
	State           PlaybackStateState     `json:"state"`
	Voice           string                 `json:"voice,omitempty,omitzero"`
}

// PlaybackStateErrorCode defines model for PlaybackState.ErrorCode.
type PlaybackStateErrorCode string

// PlaybackStateState defines model for PlaybackState.State.
type PlaybackStateState string

// SetPositionRequest defines model for SetPositionRequest.
type SetPositionRequest struct {
	// BookID Example: book-1
	BookID      string `json:"book_id"`
	CurrentByte *int64 `json:"current_byte"`
}

// StartPlaybackRequest defines model for StartPlaybackRequest.
type StartPlaybackRequest struct {
	// BookID Example: book-1
	BookID    string `json:"book_id"`
	ChunkSize *int   `json:"chunk_size,omitempty"`

	// Voice Example: Microsoft Irina Desktop
	Voice string `json:"voice,omitempty,omitzero"`
}

// Voice defines model for Voice.
type Voice struct {
	// Name Example: Microsoft Irina Desktop
	Name string `json:"name"`
}

// VoicesResponse defines model for VoicesResponse.
type VoicesResponse struct {
	Voices []Voice `json:"voices"`
}

// Error defines model for Error.
type Error = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// AddBookJSONRequestBody defines body for AddBook for application/json ContentType.
type AddBookJSONRequestBody = AddBookRequest

// StartPlaybackJSONRequestBody defines body for StartPlayback for application/json ContentType.
type StartPlaybackJSONRequestBody = StartPlaybackRequest

// SetPlaybackPositionJSONRequestBody defines body for SetPlaybackPosition for application/json ContentType.
type SetPlaybackPositionJSONRequestBody = SetPositionRequest
